### ISSUE TITLE
As a user, I can import an Isis module that has a submodule named bundle.

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/autocnet#166]
Desired API syntax

```python
import isis
import isis.control as control #  This is bundle.
```

**Comment by Kelvinrr** [comment]
May be difficult to do from the SIP level because of the way it handles namespaces: http://pyqt.sourceforge.net/Docs/sip4/specification_files.html#namespaces

It is why the wrapped python module has a weird naming convention with the Isis namespace within bundle. Because that namespace is used everywhere, I don't think we can do too much about it on the SIP side. Renaming the module to `isis` will cause it to still have the C++ namespace `Isis` inside of it as a Python class with the contents as attributes. 
 
Phil from the PyQt mailing list seems to recommend using SIP to generate the original code then creating wrapper classes in python to get the desired structure: https://riverbankcomputing.com/pipermail/pyqt/2009-July/023550.html 

Granted, that message is from 2009, might be worth posting a new question to see if there is some new feature we can leverage. Just wanted to point out why it was the way it was.

**Comment by jlaura** [comment]
looks like the best bet then is to rename bundle.so to isis.so and test if we can use a line in an __init__.py file to munge the namespace.

This type of munging falls over to #168 then, where we can either (1) make a call to a pandas constructor within the *.sip file or  (2) leave the *.sip clean and then wrap the bundle class in our own container.  My preference would be to solve our issues with (2).  Maybe on Monday we can sit down and outline what the structure of the wrapper will be.

**Comment by jlaura** [comment]
Moved into the ISIS3 sip wrapper repo.

https://github.com/USGS-Astrogeology/sip_wrappers/issues/10
