### ISSUE TITLE
Add the ability to get objects by ID via the database model

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/autocnet#313]
It would be handy to be able to get a point, image, edge, overlap, measure, match, etc. via its ID. This would allow us to move several sqlalchemy queries into the model.

For example, right now to get an overlap by its ID you have to do this:
```
res = session.query(Overlay).filter(Overlay.id == id)
    if res is None:
        print('Could not find overlap with ID', id)
        sys.exit(1)
    overlap = res.first()
```

It would be much nicer to just do

```
overlap = Overlap[id]
```

This may be able to be done via `__getItem__`

**Comment by jlaura** [comment]
Using `__getitem__` we also want to be able to support slices. Maybe something like this:

```python
class Foo:
    def __getitem__(self, val):
        if isinstance(val, slice):
            start, stop, step = slice
            val = range(start, stop, step)
        return # the result of the query where the filter call uses `.in_` and the `val` is always a list.
```

**Comment by jlaura** [comment]
Looked into this and I do not know if it is doable. A few issues:

- The table (e.g., Images) is of type DeclarativeBase which does not / can not have a `__getitem__`
- The DeclarativeMeta already supports the following: `session.Query(table).get(n)`, where `n` is the primary key
  - This only supports access for a single element / pk
- Session - we should pause to think about session lifecycle and session scoping. Specifically, https://docs.sqlalchemy.org/en/13/orm/session.html

**Comment by jlaura** [comment]
Reading more about this with a ☕️ fueled brain. This looks like a poor idea because we want to keep the session external from the functions. I could see moving to using:

```python
### another way (but again *not the only way*) to do it ###

from contextlib import contextmanager

@contextmanager
def session_scope():
    """Provide a transactional scope around a series of operations."""
    session = Session()
    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        session.close()


def run_my_program():
    with session_scope() as session:
        ThingOne().go(session)
        ThingTwo().go(session)
``` 
(From the docs). This would get rid of a lot of the session boiler plate, but it looks like keeping the session out of the model descriptions is preferable. I am less concerned about the `create` method adopting a pattern, because the session is passed in and the method is a classmethod. We still have a clean separation. 

Another option to do this might be something along these lines:

```python
class ImagesTable(object):
    def __init__(self, declarativemeta):
        # e.g., Images or Matches
        self.declarativemeta = declarativemeta
        
    def __getitem__(self, val):
        if isinstance(val, slice):
            val = range(slice.start, slice.stop, slice.step)
        session = Session()
        res = session.query(self.declarativemeta).filter(self.declarativemeta.in_(vals)).all()
        session.close()
        if res is None:
            raise KeyError
        return res
```

The idea here being that we wrap every schema/row/object declaration into a table object that then supports the interface that we want. It would be possible to move the create over into here as well. It might also be nice to push the context manager into here as well. Thoughts?

**Comment by jessemapel** [comment]
Similar to #314, this isn't worth worrying about right now
