### ISSUE TITLE
Switch from pysis to kalasiris?

### ISSUE THREAD

**Issue by rbeyer** [USGS-Astrogeology/autocnet#570]
Full disclosure: I'm the primary developer of [kalasiris](https://kalasiris.readthedocs.io/).

I'd like to suggest replacing the use of the *pysis* package for running ISIS commands in *autocnet* with the *kalasiris* package.

*kalasiris* and *pysis* have similar [functionality](https://kalasiris.readthedocs.io/en/latest/pysis.html), and you can read that link for more information.

However, for this project, the additional motivators are:
* The *pysis* package is not actively maintained (its owner has left Planetary Sciences), and *kalasiris* is.
* The *pysis* package was written against Python 2.7 (now end-of-lifed), and still appears to work with modern versions of Python, but *kalasiris* is written in Python 3 and has a robust test suite ([![codecov](https://codecov.io/gh/rbeyer/kalasiris/branch/main/graph/badge.svg?token=TL5UZUQHRC)](https://codecov.io/gh/rbeyer/kalasiris)) against versions of ISIS from 3.9 to 5.0.
* *kalasiris* was recently approved as a PlanetaryPy Affiliated Package.
* I'm volunteering to submit a PR with the changes needed for this transition.

My initial analysis of *autocnet* indicates that this transition should be transparent and easy.  The *pysis* package is imported in these *autocnet* files:

<details>
  <summary>grep -r pysis *</summary>

```
autocnet/cg/change_detection.py:import pysis
autocnet/cg/change_detection.py:    isis_null = pysis.specialpixels.SPECIAL_PIXELS['Real']['Null']
autocnet/cg/change_detection.py:    isis_null = pysis.specialpixels.SPECIAL_PIXELS['Real']['Null']
autocnet/utils/hirise.py:from pysis import isis
autocnet/utils/hirise.py:from pysis.exceptions import ProcessError
autocnet/matcher/subpixel.py:from pysis.exceptions import ProcessError
autocnet/spatial/isis.py:from pysis import isis
autocnet/spatial/isis.py:from pysis.exceptions import ProcessError
autocnet/spatial/isis.py:                    raise ProcessError(returncode=1, cmd=['pysis.campt()'], stdout=r, stderr=r['GroundPoint']['Error'])
autocnet/spatial/isis.py:                raise ProcessError(returncode=1, cmd=['pysis.campt()'], stdout=pvlres, stderr=pvlres['GroundPoint']['Error'])
autocnet/spatial/overlap.py:from pysis.exceptions import ProcessError
bin/acn_cd:import pysis
bin/acn_cd:from pysis.exceptions import ProcessError
bin/acn_cd:from pysis import isis
conda/meta.yaml:      - pysis>=0.1.1
conda/meta.yaml:      - pysis
docs/users/workshops/FY21_workshop/03_24_2021_workshop/4_network_generation.ipynb:    "# We don't technically need this but it avoids a warning when importing pysis\n",
docs/users/workshops/FY21_workshop/2_plio_analysis.ipynb:    "# PLIO uses pysis for some other things. We don't technically need this but it avoids a warning.\n",
docs/users/workshops/FY21_workshop/4_network_generation.ipynb:    "# We don't technically need this but it avoids a warning when importing pysis\n",
environment-pvl1.yml:  - pysis
environment.yml:  - pysis
notebooks/hirise_registration.ipynb:    "from pysis import isis\n",
notebooks/hirise_registration.ipynb:    "from pysis.exceptions import ProcessError\n",
notebooks/hirise_registration.ipynb:    "import pysis\n",
notebooks/hirise_registration.ipynb:    "isis_null = pysis.specialpixels.SPECIAL_PIXELS['Real']['Null']\n",
notebooks/blob_detection.ipynb:    "import pysis\n",
notebooks/blob_detection.ipynb:    "from pysis import isis\n",
notebooks/blob_detection.ipynb:    "from pysis.exceptions import ProcessError\n"
notebooks/blob_detection.ipynb:    "isis_null = pysis.specialpixels.SPECIAL_PIXELS['Real']['Null']\n",
```

</details>

Of course, if we don't want to change, then that's fine, but I'd like some consensus on whether this PR would be well-received or not before I start hacking.

**Comment by jessemapel** [comment]
This seems like a simple swap and low impact. I don't see a huge benefit here other than potentially better support.

**Comment by jlaura** [comment]
I agree that this is a great change. We also use pysis in the same way across modules, so I would advocate refactoring the usages into a single interface that is then used across autocnat. This should make testing easier as well since we can mock the interface instead of having to mock/fake pysis across multiple places.

I can make the swap in the non-change detection locations. @Kelvinrr are you able to make the swap in the change detection locations once I have the interface up?

**Comment by rbeyer** [comment]
What "interface" are you talking about, exactly?  It is literally just making some minor changes in the calls, and catching subprocess.CalledProcessErrors instead of pysis's custom ProcessErrors.  Am I missing something?

I've already got a PR halfway done on making these changes and writing tests for them, but I'll stop doing that until I'm straightened out.

**Comment by Kelvinrr** [comment]
@jlaura +1 on making those changes. 

@rbeyer I agree there doesn't really seem to be any necessary API changes as it all looks exactly the same from skimming the code. One thing I would personally like is something like [syntax sugar for image to ground and ground to image](https://github.com/USGS-Astrogeology/pysis/blob/master/pysis/sugar.py) as we leverage that a lot and I believe is more appropriate within kalasiris over within Autocnet. Seems like the kalasiris equivalent is the k_funcs module? Part of migrating work can be me (or whoever gets to it first)  PR-ing those into kalasiris.

**Comment by rbeyer** [comment]
@Kelvinrr hmm, those look neat--and useful.

My concern is that I'm (probably irrationally) defensive about dependencies for *kalasiris*.  It currently has none (well, one if you consider ISIS itself a "dependency"), which makes it very simple, and very flexible.  The functions you have there would add a *numpy* and a *pvl* dependency.  These are both reasonably-behaved, but still.

These functions seem to be implemented in *autocnet*'s spatial/isis.py module.  Let me spend some quality time with them, and do some more thinking.  At first blush, it looks like *numpy* is just used to wrap lists and return them, so you could just have these functions return Python lists, and if the caller wanted them to be *numpy* arrays, they would be responsible for converting them to that.  Not sure about *pvl* that might be harder to elide.  Lemme think and play.

There are certainly ways to add optional dependencies to libraries, and maybe that would be an option here: you could still install *kalasiris* without any dependencies, you just wouldn't be able to use these functions, but if you did, you could.

**Comment by Kelvinrr** [comment]
@rbeyer hmmmm, I'll mess with this a bit in a Jupyter notebook to get an idea of how outputs and logging works from a user perspective for kalasiris. The numpy stuff can be replaced with pure python as it's mostly for convenience like you said, but I believe PVL parsing would be very valuable for converting output strings to something more parsable. We also should be removing Isis.py, it's dragged for a while since I didn't feel 100% comfortable of relying on code that wasn't really maintained outside of our fork.

**Comment by rbeyer** [comment]
I got a better understanding `spatial/isis.py` while I worked on #573.  Its real power for providing simplified interfaces via `ground_to_image()` and `image_to_ground()` come from the use of *numpy* and *pvl*, as we previously discussed.

As we talked about, you could pretty easily factor *numpy* out of there, and just deal with list-likes.  Removing *pvl* would be much more difficult.  It could be done by having `point_info()` return the output as a fat string (expecting users to run `pvl.loads()` on the output).  But this leaves `ground_to_image()` and `image_to_ground()` in a funny place.  You could probably regex the bits you needed out of the string without too much trouble, but that seems foolish when *pvl* exists and does the job.

I'm still not sure that it would be good to move this module's functions to *kalasiris* because of those dependencies.  *kalasiris* is meant to be a really thin wrapper around the calls to ISIS and not get away from itself by implementing complicated interfaces, which these feel like to me.  They're clearly useful, but they have complexity.  However, like I said, we could implement them in a way that the default install of *kalasiris* doesn't use them, and installs fine without them.  But if you have those modules available, then *kalasiris* has some extra powers.

**Comment by jlaura** [comment]
Personally, I would caution against the optional dependencies for two reasons. First, they make testing a pain. I think that this is a pretty minor inconvenience. Second, if you have optional dependencies and the library ends up getting used primarily with those dependencies then you really do not have optional dependencies. What is the default, *kalasiris* with or without *pvl*? Whichever is the default is what users will see 99% of the time. 

The other thing to consider is the environment that *kalasiris* is going to install into. I would be confident that *pvl* and *numpy* will be in that environment because they are primary components of the planetary python computing stack. Maybe that is an argument to support optional dependencies?

If *kalasiris* is going to be a super thin wrapper, I would suggest it stay that way because it supports use in a super stripped down environment. I don't know that I buy that though because ISIS is a super fat environment and is a dependency.

Just some thoughts! Very glad to see this conversation!
